#!/usr/bin/env python
# -*- coding: utf-8 -*-
variable = "testing"
print "das ist ein {0!s}".format(variable)
exec(variable)
eval(varialbe)
eval(variable)
eval("print variable")
exec(variable)
eval(varialbe)
eval(variable)
eval("print variable")
print "das {0!s}".format("ist")
eval("print variable")
variable = "testing"
print "das ist ein {0!s}".format(variable)
print "das ist ein {0!s}".format(variable)
variable = "testing"
print "das ist ein {0!s}".format(variable)
print "das ist ein {0!s}".format(variable)
exec(variable)
eval(varialbe)
eval(variable)
eval("print variable")
print "das {0!s}".format("ist")
eval("print variable")
variable = "testing"
print "das ist ein {0!s}".format(variable)
print "das ist ein {0!s}".format(variable)
exec(variable)
eval(varialbe)
eval(variable)
eval("print variable")
print "das {0!s}".format("ist")
eval("print variable")
eval("print variable")
variable = "testing"
print "das ist ein {0!s}".format(variable)
print "das ist ein {0!s}".format(variable)
exec(variable)
eval(varialbe)
eval(variable)
eval("print variable")
print "das {0!s}".format("ist")
eval("print variable")
eval("print variable")
variable = "testing"
print "das ist ein {0!s}".format(variable)
print "das ist ein {0!s}".format(variable)
exec(variable)
eval(varialbe)
eval(variable)
eval("print variable")
print "das {0!s}".format("ist")
eval("print variable")
variable = "testing"
print "das ist ein {0!s}".format(variable)
print "das ist ein {0!s}".format(variable)
exec(variable)
eval(varialbe)
eval(variable)
eval("print variable")
print "das {0!s}".format("ist")
eval("print variable")
eval("print variable")
variable = "testing"
print "das ist ein {0!s}".format(variable)
print "das ist ein {0!s}".format(variable)
exec(variable)
eval(varialbe)
eval(variable)
eval("print variable")
print "das {0!s}".format("ist")
eval("print variable")
eval("print variable")
variable = "testing"
print "das ist ein {0!s}".format(variable)
print "das ist ein {0!s}".format(variable)
exec(variable)
eval(varialbe)
eval(variable)
eval("print variable")
print "das {0!s}".format("ist")
eval("print variable")
eval("print variable")
eval(varialbe)
eval(variable)
eval("print variable")
print "das {0!s}".format("ist")
eval("print variable")
eval("print variable")
eval("print variable")
print "das {0!s}".format("ist")
eval("print variable")
eval("print variable")
eval(varialbe)
eval(variable)
eval("print variable")
print "das {0!s}".format("ist")
eval("print variable")
eval("print variable")
eval("print variable")
eval("print variable")
eval("print variable")
eval("print variable")
##### 5 more
eval("print variable")
eval("print variable")
eval("print variable")
eval("print variable")
eval("print variable")
eval("print variable")
##### 4 more
eval("print variable")
eval("print variable")
eval("print variable")
eval("print variable")
##### 3 more
eval("print variable")
eval("print variable")
eval("print variable")
##### 2 more
eval("print variable")
eval("print variable")
##### 1 more
eval("print variable")
##### 3 more
eval("print variable")
eval("print variable")
eval("print variable")
##### 2 more
eval("print variable")
eval("print variable")
##### 4 more
eval("print variable")
eval("print variable")
eval("print variable")
eval("print variable")
##### 5 more
eval("print variable")
eval("print variable")
eval("print variable")
eval("print variable")
eval("print variable")
##### 4 more
eval("print variable")
eval("print variable")
eval("print variable")
eval("print variable")
##### 5 more
eval("print variable")
eval("print variable")
eval("print variable")
eval("print variable")
eval("print variable")
##### 4 more
eval("print variable")
eval("print variable")
eval("print variable")
eval("print variable")
##### 3 more
eval("print variable")
eval("print variable")
eval("print variable")
##### 2 more
eval("print variable")
eval("print variable")
##### 1 more
eval("print variable")
